name: Deploy to Dev Server (Develop)

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Dev Server (Develop)
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 21458 $SSH_USERNAME@137.59.53.70 << 'EOF'
            set -e
            cd /root/acdoctorserver/acdoctorserverapp
            git pull origin develop
            export NVM_DIR=/root/.nvm
            source /root/.nvm/nvm.sh
            npm ci
            npm run stop:server
            npm run start:server
          EOF
